### PR TITLE
version bump to `0.0.19`

### PR DESCRIPTION
**Pull request by perlinm**

### CODE REVIEW

**Comment by perlinm** [comment]
@vtomole do you have any idea why pytest+coverage checks fail regularly?  Like [here](https://github.com/Infleqtion/qLDPC/actions/runs/12001337139/job/33451699037?pr=145).  Rerunning them usually fixes it...

**Comment by bharat-thotakura** [comment]
> ... Like [here](https://github.com/Infleqtion/qLDPC/actions/runs/12001337139/job/33451699037?pr=145). Rerunning them usually fixes it...

Perhaps this isn't what you're asking about, but it looks like that instance did not 'fail' per se but rather was just canceled from hitting the [time out limit](https://github.com/Infleqtion/qLDPC/blob/10cb618028e77ce6f8237a21f37c411ce7d4f8fc/.github/workflows/ci.yml#L89). This could be happening more recently now if your codebase has expanded and pytest+coverage takes a bit more time to run and/or new/updated dependencies maybe taking slightly longer to setup or something. Still, I think repeated runs usually fix this due to caching, but I would recommend just bumping your CI timeout by 1 minute if it's a regular occurrence

**Comment by vtomole** [comment]
+1 to Bharath. Try bumping https://github.com/Infleqtion/qLDPC/blob/10cb618028e77ce6f8237a21f37c411ce7d4f8fc/.github/workflows/ci.yml#L89

**Comment by perlinm** [comment]
That makes sense, thank you!

**Pull request merged**
