### PR TITLE
Add github continuous integration workflow

### PR DESCRIPTION
**Pull request by perlinm**
Based on [these](https://github.com/Infleqtion/client-superstaq/blob/main/.github/workflows/ci.yml) continuous integration tests in `client-superstaq`

### CODE REVIEW

**Comment by perlinm** [comment]
Not sure what to do about this failing type check:
image
`./checks/mypy_.py` works for me locally

**Comment by vtomole** [comment]
Which package are you using that has the `google` dependency in `site-packages` that mypy is trying to check?

**Comment by richrines1** [comment]
it's picking up on this import in cvxpy, which is only relevant to `cvxpy[ortools]` (and so the package isn't required otherwise): https://github.com/cvxpy/cvxpy/blob/ad6cafb117d24f82e094147e07a5f77a022ad1a8/cvxpy/reductions/solvers/conic_solvers/glop_conif.py#L49

the quick fix is to disable the `install_types` option for mypy (and add any relevant types- packages to the dev requirements)

**Comment by richrines1** [comment]
apparently this is a known issue https://github.com/python/typeshed/issues/11254

the best solution is probably just to pin
```
types-protobuf <= 4.24.0.4
```
for now (and unpin once that issue is resolved)

**Comment by perlinm** [comment]
Awesome that worked!  Thank you @richrines1!

**Pull request merged**
